// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8R9jyoeXF0G1fIgT_CIQoYw7FkauUco',
    appId: '1:626159986782:android:74693fab5d468ec9edeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    storageBucket: 'study-app-dacd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdVz--U96UUc0yX2uVbsEfa7L3NmFdx0',
    appId: '1:626159986782:ios:43bf5b3326772f1aedeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    storageBucket: 'study-app-dacd5.appspot.com',
    androidClientId: '626159986782-sgcebfmi7156hhll7kae6nf3kio2ankq.apps.googleusercontent.com',
    iosClientId: '626159986782-ptuvm1svs1b1veqnm8os0sa6kh9ap1k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.study.flutterStudyApp',
  );
}
