// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA08qyozha9OTsWxp6arCcxQy07kRWX5E',
    appId: '1:626159986782:web:6c7053e3f8a67a5aedeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    authDomain: 'study-app-dacd5.firebaseapp.com',
    storageBucket: 'study-app-dacd5.appspot.com',
    measurementId: 'G-CWNKYXXSW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8R9jyoeXF0G1fIgT_CIQoYw7FkauUco',
    appId: '1:626159986782:android:74693fab5d468ec9edeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    storageBucket: 'study-app-dacd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdVz--U96UUc0yX2uVbsEfa7L3NmFdx0',
    appId: '1:626159986782:ios:43bf5b3326772f1aedeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    storageBucket: 'study-app-dacd5.appspot.com',
    iosBundleId: 'com.example.study.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdVz--U96UUc0yX2uVbsEfa7L3NmFdx0',
    appId: '1:626159986782:ios:4f8c7339a164b5d5edeccf',
    messagingSenderId: '626159986782',
    projectId: 'study-app-dacd5',
    storageBucket: 'study-app-dacd5.appspot.com',
    iosBundleId: 'com.example.study.flutterStudyApp.RunnerTests',
  );
}
